alias kg='kubectl get'
alias kga='kubectl get all'
alias kgcm='kubectl get configmap'
alias kgp='kubectl get pods'
alias kgpa='kubectl get pods --all'
alias kn='kubectl config set-context --current --namespace '
alias kl='kubectl logs'
alias kpf='kubectl port-forward'
alias kctx='kubectl config use-context'
alias kgaa='kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found'
