# add brew repos
# can untap homebrew/core and homebrew/cask since v4.0
tap "homebrew/services"

# general utilities
brew "golang"
brew "jq"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rbenv"
brew "ripgrep"

cask "brave-browser"
cask "iterm2"
cask "rectangle"
cask "slack"
cask "spotify"
cask "syncthing"
