# Stuff from old .zshrc
zstyle :compinstall filename '/home/loki/.zshrc'
autoload -Uz compinit
compinit

# zsh options
ZSH_THEME="loki"
HYPHEN_INSENSITIVE="true"

# omz plugins
plugins=(git)

export ZSH=/home/loki/.oh-my-zsh
source $ZSH/oh-my-zsh.sh

[[ -f /usr/share/nvm/init-nvm.sh ]] && . /usr/share/nvm/init-nvm.sh
[[ -f $HOME/.zsh_aliases ]] && . $HOME/.zsh_aliases
