zstyle ':completion:*' completer _complete _ignored _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle :compinstall filename "${ZDOTDIR}/.zshrc"

autoload -Uz compinit
compinit

export ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="loki"
HYPHEN_INSENSITIVE="true"

plugins=(
	git
	zsh-nvm
)

source "${ZSH}/oh-my-zsh.sh"

[[ -f "${ZDOTDIR}/.zsh_aliases" ]] && . "${ZDOTDIR}/.zsh_aliases"
[[ -f /usr/share/nvm/init-nvm.sh ]] && . /usr/share/nvm/init-nvm.sh
